name: valgrind

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'What branch to run Valgrind on'
        required: true
        default: 'master'
        type: string

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          submodules: true
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ inputs.branch }}
          submodules: true
      - name: install valgrind
        run: sudo apt-get install valgrind
      - name: build
        run: |
          make BUILD_TYPE=RelWithDebInfo
      - name: test
        run: |
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./build/run-test262 -m -c test262.conf -a
